version: '3.8'
x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "{MYSQL_PASSWORD:?error}"
    MYSQL_ROOT_PASSWORD: "{MYSQL_ROOT_PASSWORD:?error}"
  panel:
    &panel-environment
    APP_URL: "https://panel.example.com"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "Asia/Jerusalem"
    APP_SERVICE_AUTHOR: "ron@yutk.in"
  mail:
    &mail-environment
    MAIL_FROM: "${SMTP_MAIL_FROM:?error}"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "${SMTP_PORT:?error}"
    MAIL_USERNAME: "${SMTP_USERNAME:?error}"
    MAIL_PASSWORD: "${SMTP_PASSWORD:?error}"
    MAIL_ENCRYPTION: "true"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#

services:

  database:
    image: library/mysql:8.0
    restart: always
    networks:
      - local
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"

  cache:
    image: redis:alpine
    restart: always
    networks:
      - local

  panel:
    image: ghcr.io/pterodactyl/panel:v1.11.10
    restart: always
    networks:
      pterodactyl:
      services:
        ipv4_address: ${IPV4_ADDR:?error}
    links:
      - database
      - cache
    volumes:
      - "panel_var:/app/var/"
      - "panel_logs:/app/storage/logs"
      - "nginx_conf:/etc/nginx/conf.d/"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      TRUSTED_PROXIES: "*"
    labels:
      # HTTP
      - "traefik.http.routers.pterodactyl_panel.entrypoints=web"
      - "traefik.http.routers.pterodactyl_panel.rule=Host(`${PANEL_DOMAIN:?error}`)"
      # - "traefik.http.routers.pterodactyl_panel.middlewares=panel_https"
      # - "traefik.http.middlewares.panel_https.redirectscheme.scheme=https"
      # HTTPS
      # - "traefik.http.routers.pterodactyl_panel-https.entrypoints=websecure"
      # - "traefik.http.routers.pterodactyl_panel-https.rule=Host(`${PANEL_DOMAIN:?error}`)"
      # - "traefik.http.routers.pterodactyl_panel-https.tls=true"
      # - "traefik.http.routers.pterodactyl_panel-https.tls.certresolver=letsencrypt"
      # - "traefik.http.services.pterodactyl_panel-https.loadbalancer.server.port=80"

volumes:
  panel_var:
  panel_logs:
  nginx_conf:
  mysql_data:

networks:
  local:
    external: false
  services:
    name: hexos-services
    external: true
